# Generated by Django 6.0.3 on 2026-04-09 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_achievement_userachievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='module',
            field=models.IntegerField(default=1),
        ),
    ]
